### ISSUE TITLE
Example spreadsheet needed

### ISSUE THREAD

**Issue by kikito** [pjungwir/rbinvoice#1]
Hello there!

I might be interested on this gem.

Is there an example input spreadsheet?

**Comment by pjungwir** [comment]
Hi Enrique,

Thanks for your interest in rbinvoice. I don't encourage you to use this
for real billing, because it's extremely immature software. To get anything
out of it, you'll need to learn the codebase and make changes here and
there. At this point I can't offer support, and I'm not worrying about
tagging stable versions, so the code may change unexpectedly. But I've
updated the README with the documentation you asked for. (I also added a
big disclaimer to warn other people. :-) If you want to make any
contributions, I'm happy to accept pull requests.

Good luck!
Paul

On Mon, Oct 1, 2012 at 2:06 PM, Enrique García notifications@github.comwrote:

> Hello there!
> 
> I might be interested on this gem.
> 
> Is there an example input spreadsheet?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/pjungwir/rbinvoice/issues/1.

## 

---

Pulchritudo splendor veritatis.

**Comment by kikito** [comment]
Thanks for the heads up. To be completely honest, I'm not sure I'll use it. But I am using google docs already for simple time tracking, so I thought why not?

I would not want to deviate another rubyist from the holy ruby path, but in case it peaks your interest, I found an example of how to do a similar time-tracking tool using Google's javascript-in-the-server solution, called "apps-script". It can be found here:

https://developers.google.com/apps-script/articles/building-sites-app

I'm not using it, but I found it interesting nevertheless.

I consider this issue closed now. Thanks for your feedback!
